name: CI/CD Pipeline

on:
  push:
    branches: ['main']  #déclenché sur push
  pull_request:
    branches: ['main'] # déclenché sur PR

jobs:

  # job 1 : LINT
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # clone le repo
      - uses: actions/setup-node@v4 # installe Node.js
        with:
          node-version: "20"
          cache: "npm"
      - run: npm ci 
      - run: npm run lint 
  
  # job 2 TEST
  test:
    name: Tests
    runs-on: ubuntu-latest
    needs: lint # lance seulement si lint passe
    steps:
      - uses: actions/checkout@v4 # clone le repo
      - uses: actions/setup-node@v4 # installe Node.js
        with:
          node-version: "20"
          cache: "npm"
      - run: npm ci 
      - run: npm test
  
  # job 3: Deploy
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' # pas de deploy sur les PR
    steps:  
      - name: Deployer vers render
        run: curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK }}"

